version: '2'
services:
    microsvc1test-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/microsvc1test/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=microsvc1test
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
